### ISSUE TITLE
为什么我在vercel中部署好了，但是看不到图片呢

### ISSUE THREAD

**Issue by aqpmzngldh** [CherryLover/image-gallery-starter#1]

**Comment by aqpmzngldh** [comment]
我设置的目录是ls，然后图片路径是:https://res.cloudinary.com/dge3vgskk/image/upload/ls/1_wj0evz.png，但是主页显示不出来图

**Comment by CherryLover** [comment]
![image](https://github.com/CherryLover/image-gallery-starter/assets/18376501/b94c253d-614d-4dd1-9254-7473df3f8719)


这几个环境变量需要检查一下

**Comment by aqpmzngldh** [comment]
![2024-05-17_121948](https://github.com/CherryLover/image-gallery-starter/assets/124235388/0ae3328a-22a7-4d5c-9e99-c187603f64af)
![777777777728](https://github.com/CherryLover/image-gallery-starter/assets/124235388/012cbdd5-517e-40cb-b877-40d2189f68e5)
麻烦看下我这个哪里的问题，前面三个参数从这里获取，第四个参数我写的ls，然后我上传了图片，图片通过https://res.cloudinary.com/dge3vgskk/image/upload/ls/1_wj0evz.png可以访问到的

**Comment by aqpmzngldh** [comment]
> ![image](https://private-user-images.githubusercontent.com/18376501/331762719-b94c253d-614d-4dd1-9254-7473df3f8719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDM2NjMsIm5iZiI6MTcxNjAwMzM2MywicGF0aCI6Ii8xODM3NjUwMS8zMzE3NjI3MTktYjk0YzI1M2QtNjE0ZC00ZGQxLTkyNTQtNzQ3M2RmM2Y4NzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAzMzYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNmIxYzBiODA2ZjhhNWIwOGQ5NmNjYTM3N2FiYjdhZWNlMmRmZmI5YjQyMmZkZTJhYWY5ZmIzZjY3YzIxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RQ7PuXEG3rEpQjVw-1WTlu_9pbnXqxGuQfnpjkJYlDI)
> 
> 这几个环境变量需要检查一下

在这里在这里

**Comment by CherryLover** [comment]
你重新复制一下试试看，注意空格，不确定是什么原因导致的

**Comment by aqpmzngldh** [comment]
> 你重新复制一下试试看，注意空格，不确定是什么原因导致的

好吧，我再重新部署下试试

**Comment by aqpmzngldh** [comment]
> 你重新复制一下试试看，注意空格，不确定是什么原因导致的

这下好了，成功的展示了，但是图片加载的时候浑浊背景一闪而过，然后有个地址访问400，不知道怎么回事
![565656565656551](https://github.com/CherryLover/image-gallery-starter/assets/124235388/fae80409-e797-441a-9fc5-acc627a0417e)

**Comment by CherryLover** [comment]
你多弄点测试图片，看看单张看不出效果

**Comment by CherryLover** [comment]
400 可能是超时了，我刚才访问你的那个 测试图片的连接，前2 次就访问失败

**Comment by aqpmzngldh** [comment]
> 400 可能是超时了，我刚才访问你的那个 测试图片的连接，前2 次就访问失败

是不是因为我没设置域名的原因呢，请问你有没有设置域名呢，我记得之前的有些项目要设置域名访问速度才能快一些

**Comment by CherryLover** [comment]
我访问的是你 cloudinary 的地址，不是你 vercel 上的地址。

我 vercel 的地址是绑定了域名的

**Comment by aqpmzngldh** [comment]
> 我访问的是你 cloudinary 的地址，不是你 vercel 上的地址。
> 
> 我 vercel 的地址是绑定了域名的

那我一会绑定域名看看，我现在的情况是，即使在我设置的ls目录下上上传了多张照片，但是项目加载的时候还是只有一张模糊背景，一闪而过，具体如下图
![111111115](https://github.com/CherryLover/image-gallery-starter/assets/124235388/ab6cddb0-596c-4a70-bebe-794203385106)
![222222226](https://github.com/CherryLover/image-gallery-starter/assets/124235388/5d47821d-d00f-4ef2-bd52-c17005dfeaf7)

**Comment by aqpmzngldh** [comment]
然后我尝试绑定域名，还是不大行，不清楚怎么回事，你看是不是因为我设置的目录是ls，然后我创建了个ls文件夹给里面添加图片，我这个操作，还有截图你看是不是有哪里不对的地方呢
![333333333333333](https://github.com/CherryLover/image-gallery-starter/assets/124235388/89af469a-4b8a-462a-96ec-fa20beddb370)

**Comment by aqpmzngldh** [comment]
要不我给我的参数全部给你，你试一下，看是不是参数的问题，可以吗

**Comment by aqpmzngldh** [comment]
400: BAD_REQUEST
Code: INVALID_IMAGE_OPTIMIZE_REQUEST
ID: sfo1::49zrh-1716007705730-6db113084490

**Comment by CherryLover** [comment]
你私聊我，微信聊吧，jiangjiwei359 微信号

**Comment by aqpmzngldh** [comment]
> 你私聊我，微信聊吧，jiangjiwei359 微信号

大佬加你了

**Comment by CherryLover** [comment]
不要使用 README 中的一键部署，会强制使用官方的模版，官方的最新模板可能更新了，不一定适用。

![image](https://github.com/CherryLover/image-gallery-starter/assets/18376501/a2a992af-a578-472b-9817-980bb6c0d16f)
